---
title: "figure-drafts"
author: "Linda Herrera, Natalie Chen, June McNally"
format: pdf
---

## Set up

### Packages

```{r}
#| label: packages
#| message: false
#| warning: false

# general use and cleaning
library(tidyverse)
library(here)
library(janitor)
library(snakecase)

# wrapping axis labels
library(scales)

# reading in .xlsx files
library(readxl)

# arranging plots
library(patchwork)

# coloring
library(wesanderson)
```

### Data

```{r}
#| label: data
#| message: false
#| warning: false

# taxonomic information
taxon_list <- read_csv(here("data", "taxon_list.csv")) 

# aquatic invertebrates
aq_ins <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                    sheet = "Aquatic Insects") 

# site information
sites <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                   sheet = "sites")

# water quality information
water_quality <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                           sheet = "Water Quality",
                           na = c("", "n/a", "N/A", "over", "173+")) 
```

## Cleaning and Wrangling 


### Cleaning

#### `sites` object

```{r}
#| label: ncos-site-object
#| message: false

# creating new object from sites
ncos_sites <- sites |> 
  # filter to only include NCOS sites sampled four times a year
  filter(sector == "NCOS" & sampling_frequency == "Quarterly")
```

#### `taxon_list` object

```{r}
#| label: cleaning-taxon-list
#| message: false

# creating new clean object from taxon_list
taxon_list_clean <- taxon_list |> 
  # converting taxon name to snake case (no spaces or capital letters,
  # only underscores)
  mutate(verbatim_name = to_any_case(verbatim_name, case = "snake"))
```

#### `water_quality` object

```{r}
#| label: water-quality-cleaning
#| message: false

water_quality_clean <- water_quality |> 
  clean_names() |> 
  semi_join(ncos_sites, by = "site") |> 
  unite("date_site", date, site, remove = TRUE) |> 
  group_by(date_site) |> 
  summarize(med_ph    = median(p_h, na.rm = TRUE),
            med_sal   = median(salinity_ppt, na.rm = TRUE),
            med_do    = median(dissolved_oxygen_mg_l, na.rm = TRUE),
            med_temp  = median(temperature_c, na.rm = TRUE)) |>   # <-- ADD THIS
  ungroup() |> 
  filter(date_site != "2022-08-12_NVBR")

```

#### `aq_ins` object

```{r}
#| label: cleaning-aq-ins
#| message: false
#| warning: false

# creating new clean object from aquatic inverts
aq_ins_clean <- aq_ins |> 
  # clean column names
  clean_names() |> 
  # filtering join: only include sites occurring in ncos_sites
  semi_join(ncos_sites, by = c("site")) |> 
  # renaming columns
  rename(date = date_on_vial) |> 
  # select columns of interest
  select(date, sample_type, site,
         ostracod,
         copepod,
         cladocera) |> 
  # filter to only include "filtered beaker" samples
  filter(sample_type %in% c("FB 250", "FB250")) |> 
  # convert the data frame to long format
  pivot_longer(cols = ostracod:cladocera,
               names_to = "taxon",
               values_to = "abundance") |> 
  # group by date, site, taxon
  group_by(date, site, taxon) |> 
  # calculate average abundance per liter (sum abundance divided by 7.5 liters)
  summarize(ave_lit = sum(abundance, na.rm = TRUE)/7.5) |> 
  # ungroup data frame
  ungroup() |> 
  # create a new column called `date_site` to join with water quality
  unite("date_site", date, site, remove = FALSE) |> 
  # join with water quality
  left_join(water_quality_clean, by = c("date_site")) |> 
  # join with taxon list
  left_join(taxon_list_clean, by = c("taxon" = "verbatim_name")) |> 
  # add full names of sites
  mutate(site_full = case_when(
    site == "NVBR" ~ "North of Venoco Bridge",
    site == "NEC" ~ "South of Venoco Bridge",
    site == "NMC" ~ "Main Channel",
    site == "NPB" ~ "South of Phelps Bridge",
    site == "NPB1" ~ "North of Phelps Bridge",
    site == "NPB2" ~ "Phelps Road",
    site == "NWP" ~  "West Pond",
    site == "NDC" ~ "Devereux Creek"
  )) |> 
  # setting factor levels for site
  mutate(site_full = fct_reorder(site_full, med_sal, .fun = "median", .na_rm = TRUE),
         site_full = fct_rev(site_full)) |> 
  
  # ADD: log+1 transform of average abundance per liter
  mutate(log_ave_lit = log(ave_lit + 1)) |>                        # <-- Fig 1, 2, 3, 4
  
  # ADD: season derived from date
  mutate(season = case_when(
    month(date) %in% c(3, 4, 5)  ~ "Spring",
    month(date) %in% c(6, 7, 8)  ~ "Summer",
    month(date) %in% c(9, 10, 11) ~ "Fall",
    month(date) %in% c(12, 1, 2) ~ "Winter"
  ),
  season = factor(season, levels = c("Spring", "Summer", "Fall", "Winter"))) |># <-- Fig 4
  mutate(taxon = factor(taxon, levels = c("copepod", "ostracod", "cladocera")))


```





